services:
 app:
   container_name: jin_app #laravel_app
   ports:
     - "3030:80" #8080:80
   build: ./Docker/App
   volumes:
     - ./src:/var/www/html
   command: >
    sh -c "chown -R www-data:www-data /var/www/html/Jin_10/storage &&
           chown -R www-data:www-data /var/www/html/Jin_10/bootstrap/cache &&
           apache2-foreground"
 db:
   image: mysql:8.0 #5.7
   container_name: jin_db #laravel_db
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: laraveldb
     MYSQL_USER: dbuser
     MYSQL_PASSWORD: dbpass
     TZ: 'Asia/Tokyo'
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   volumes:
     - ./Docker/DB/volume:/var/lib/mysql
     - ./Docker/DB/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 43306:3306 #13306:3306
 adminer:
    container_name: jin #adminer 
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 3033:8080 #8088:8080
    depends_on:
      - db